#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pysnmp
Version  : 4.4.9
Release  : 30
URL      : https://files.pythonhosted.org/packages/37/0b/881859e98e05fefee3625637a1e87cb2ba8c550613c5ccb29910ad0efe66/pysnmp-4.4.9.tar.gz
Source0  : https://files.pythonhosted.org/packages/37/0b/881859e98e05fefee3625637a1e87cb2ba8c550613c5ccb29910ad0efe66/pysnmp-4.4.9.tar.gz
Summary  : SNMP library for Python
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause
Requires: pysnmp-license = %{version}-%{release}
Requires: pysnmp-python = %{version}-%{release}
Requires: pysnmp-python3 = %{version}-%{release}
Requires: pyasn1
BuildRequires : buildreq-distutils3

%description
SNMP library for Python
-----------------------
[![PyPI](https://img.shields.io/pypi/v/pysnmp.svg?maxAge=2592000)](https://pypi.python.org/pypi/pysnmp)
[![Python Versions](https://img.shields.io/pypi/pyversions/pysnmp.svg)](https://pypi.python.org/pypi/pysnmp/)
[![Build status](https://travis-ci.org/etingof/pysnmp.svg?branch=master)](https://travis-ci.org/etingof/pysnmp)
[![GitHub license](https://img.shields.io/badge/license-BSD-blue.svg)](https://raw.githubusercontent.com/etingof/pysnmp/master/LICENSE.rst)

%package license
Summary: license components for the pysnmp package.
Group: Default

%description license
license components for the pysnmp package.


%package python
Summary: python components for the pysnmp package.
Group: Default
Requires: pysnmp-python3 = %{version}-%{release}

%description python
python components for the pysnmp package.


%package python3
Summary: python3 components for the pysnmp package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pysnmp package.


%prep
%setup -q -n pysnmp-4.4.9

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1549736374
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pysnmp
cp LICENSE.rst %{buildroot}/usr/share/package-licenses/pysnmp/LICENSE.rst
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pysnmp/LICENSE.rst

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
